name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      env:
        Flutterwave: ${{secrets.FLUTTERWAVE}}
      run: dotnet test --no-restore --verbosity normal
   
  publish_nuget:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: 'Flutterwave/Flutterwave.csproj'
        NUGET_KEY: ${{ secrets.NUGET }}
