name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      env:
        Flutterwave: ${{secrets.FLUTTERWAVE}}
      run: dotnet test --no-restore --verbosity normal
   
  publish_nuget:
    name: deploy to nuget
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: 'Flutterwave/Flutterwave.csproj'
        NUGET_KEY: ${{ secrets.NUGET }}
    - name: Start github package
      run: dotnet nuget add source https://nuget.pkg.github.com/Bracketcore/index.json -n github -u Bracketcore -p ${{secret.GH_PACKAGE_PAUL}}
    - name : echo 
      run: echo  ${{secret.GH_PACKAGE_PAUL}}
    - name: publish to github package
      run: dotnet nuget push "bin/Release/*.nupkg" --source "github"
